spring:
  application:
    name: rest-with-spring-boot-java-bruno
  
  datasource:
    url: jdbc:postgresql://localhost:5433/rest_with_spring_boot_bruno?autoreconnect=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
  
  sql:
    init:
      platform: postgres
